### ISSUE TITLE
[BUG] Config setting is not working

### ISSUE THREAD

**Issue by kyurii** [alimoncul/sfcc-wildcard#1]
Error when trying to open a file: 
"Cartridge path is not set, extension will not work!"
 "Error while trying to get the cartridge path through site.xml" 

While I do have site.xml in my data_impex folder and I added the path to extension settings.

**Comment by alimoncul** [comment]
Hey @kyurii it should be fixed in version 0.0.9

https://github.com/alimoncul/sfcc-wildcard/compare/v0.0.8...v0.0.9
